### PR TITLE
[qmf] Add find routine to find calendar parts in a message. Contributes JB#9683

### PR DESCRIPTION
**Pull request by VDVsx**

### CODE REVIEW

**Comment by VDVsx** [comment]
@matthewvogt Please have a look. thx

**Comment by matthewvogt** [comment]
I think is ok for here, but I wouldn't like it to go upstream.  We really need a function that takes a predicate functor and finds the first part (or all parts) for which the predicate returns true.

Alternatively, we could use std::find_if to do that, and add conforming iterators that would allow a part container's subparts to be iterated over.

**Comment by VDVsx** [comment]
there's already part of it, but not very used inside qmf: bool QMailMessagePartContainer::foreachPart(F func)

**Comment by matthewvogt** [comment]
Oh, well probably better to use that function than to add this one.

**Comment by VDVsx** [comment]
I could implement this entirely in the nemo side using that function and some helper, but IMO is better to add this functionality to QMF, since it already offers similar functions for other parts, so even if I use the functor a new function should be added to QMF side for this detection.

**Comment by matthewvogt** [comment]
Well, it already offers that functionality for some features which are inherent in mail handling, like the first text part or first html part.  But I don't see that a calendar part is really inherent to email, we could then use the same argument to add any type of part in common use...

**Comment by VDVsx** [comment]
Replaced by https://github.com/nemomobile/nemo-qml-plugin-email/pull/138

**Pull request closed without merging**
